### ISSUE TITLE
can't npm install after fresh checkout

### ISSUE THREAD

**Issue by vikbert** [nodegui/svelte-nodegui#38]
hello, I cloned the repo and do "npm install", but got the following error that I couldn't fix by myself.

_

> info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
> 2 info using npm@6.14.10
> 3 info using node@v12.10.0
> 4 verbose npm-session 6d39a763f88c3b4a
> 5 silly install runPreinstallTopLevelLifecycles
> 6 silly preinstall svelte-nodegui-starter@1.0.1
> 7 info lifecycle svelte-nodegui-starter@1.0.1~preinstall: svelte-nodegui-starter@1.0.1
> 8 silly install loadCurrentTree
> 9 silly install readLocalPackageData
> 10 timing stage:loadCurrentTree Completed in 7ms
> 11 silly install loadIdealTree
> 12 silly install cloneCurrentTreeToIdealTree
> 13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
> 14 silly install loadShrinkwrap
> 15 timing stage:loadIdealTree:loadShrinkwrap Completed in 182ms
> 16 silly install loadAllDepsIntoIdealTree
> 17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 232ms
> 18 timing stage:loadIdealTree Completed in 479ms
> 19 silly currentTree svelte-nodegui-starter@1.0.1
> 20 silly idealTree svelte-nodegui-starter@1.0.1
> 20 silly idealTree ├── @babel/code-frame@7.12.13
> 20 silly idealTree ├── @babel/helper-validator-identifier@7.12.11
> ...
> ...
> 10275 silly saveTree   │   ├─┬ source-map-support@0.5.19
> 10275 silly saveTree   │   │ └── buffer-from@1.1.1
> 10275 silly saveTree   │   └── source-map@0.7.3
> 10275 silly saveTree   ├── watchpack@2.1.1
> 10275 silly saveTree   └─┬ webpack-sources@2.2.0
> 10275 silly saveTree     └── source-list-map@2.0.1
> 10276 verbose stack Error: @nodegui/nodegui@0.25.0 postinstall: `cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)`
> 10276 verbose stack Exit status 1
> 10276 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 10276 verbose stack     at EventEmitter.emit (events.js:209:13)
> 10276 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 10276 verbose stack     at ChildProcess.emit (events.js:209:13)
> 10276 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 10276 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> 10277 verbose pkgid @nodegui/nodegui@0.25.0
> 10278 verbose cwd /Users/zhoux/sites/github/svelte-projects/svelte-nodegui-starter
> 10279 verbose Darwin 18.7.0
> 10280 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> 10281 verbose node v12.10.0
> 10282 verbose npm  v6.14.10
> 10283 error code ELIFECYCLE
> 10284 error errno 1
> 10285 error @nodegui/nodegui@0.25.0 postinstall: `cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)`
> 10285 error Exit status 1
> 10286 error Failed at the @nodegui/nodegui@0.25.0 postinstall script.
> 10286 error This is probably not a problem with npm. There is likely additional logging output above.
> 10287 verbose exit [ 1, true ]

_

**Comment by vikbert** [comment]
It failed on 

> Minimal Qt 5.14.1 setup:
> Archive already exists at /Users/zhoux/Library/Caches/nodegui-mini-qt-nodejs/5.14.1-0-202001241000qttools-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z. Skipping download....
> Extracting /Users/zhoux/Library/Caches/nodegui-mini-qt-nodejs/5.14.1-0-202001241000qttools-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z to /Users/zhoux/sites/github/svelte-projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/miniqt ...
> Archive already exists at /Users/zhoux/Library/Caches/nodegui-mini-qt-nodejs/5.14.1-0-202001241000qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z. Skipping download....
> Extracting /Users/zhoux/Library/Caches/nodegui-mini-qt-nodejs/5.14.1-0-202001241000qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z to /Users/zhoux/sites/github/svelte-projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/miniqt ...
> Qt Tools for Minimal Qt: 5.14.1 installation was setup successfully.  outDir: /Users/zhoux/sites/github/svelte-projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/miniqt
> Qt Base for Minimal Qt: 5.14.1 installation was setup successfully.  outDir: /Users/zhoux/sites/github/svelte-projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/miniqt
> 
> > @nodegui/nodegui@0.25.0 prebuild:install /Users/zhoux/sites/github/svelte-projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui
> > prebuild-install --backend=cmake-js --runtime=napi --verbose
> 
> prebuild-install info begin Prebuild-install version 5.3.6
> prebuild-install info looking for cached prebuild @ /Users/zhoux/.npm/_prebuilds/f8b84e-nodegui-v0.25.0-napi-v3-darwin-x64.tar.gz
> prebuild-install http request GET https://github.com/nodegui/nodegui/releases/download/v0.25.0/nodegui-v0.25.0-napi-v3-darwin-x64.tar.gz
> prebuild-install http 404 https://github.com/nodegui/nodegui/releases/download/v0.25.0/nodegui-v0.25.0-napi-v3-darwin-x64.tar.gz
> prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc= platform=darwin)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @nodegui/nodegui@0.25.0 prebuild:install: `prebuild-install --backend=cmake-js --runtime=napi --verbose`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the @nodegui/nodegui@0.25.0 prebuild:install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:

**Comment by shirakaba** [comment]
> npm ERR! Failed at the @nodegui/nodegui@0.25.0 prebuild:install script.

That’s failed on one of NodeGUI’s install scripts; could you file this issue on the NodeGUI repo instead? I myself am not sure how its installation process works.

**Comment by shirakaba** [comment]
Thought: it may (or may not) be something to do with the path at which you installed it containing unsafe punctuation:

https://github.com/nodegui/nodegui/issues/827
