### ISSUE TITLE
Typos in license in npm website

### ISSUE THREAD

**Issue by justanotheranonymoususer** [nodegui/svelte-nodegui#39]
There are several typos here in the license text:
https://www.npmjs.com/package/@nodegui/nodegui/v/0.0.11?activeTab=readme#license

I don't know how to contribute a fix.

**Comment by shirakaba** [comment]
That’s the readme for `@nodegui/nodegui`; could you file the issue on that repo instead, please?

**Comment by m417z** [comment]
https://github.com/nodegui/nodegui/issues/819
