### ISSUE TITLE
native module error even if recompiled

### ISSUE THREAD

**Issue by cicada1993** [nodegui/svelte-nodegui#51]
WARNING in ./node_modules/node-fetch/lib/index.mjs 156:11-38
Module not found: Error: Can't resolve 'encoding' in 'D:\Workspace\svelte-nodegui-starter\node_modules\node-fetch\lib'
 @ ./src/components/StepTwo.svelte 19:0-31 126:25-30
 @ ./src/App.svelte 26:0-50 50:15-22
 @ ./src/app.ts 2:0-31 3:14-17

after recompiled by npm rebuild --nodedir=node_modules/@nodegui/qode

also error

**Comment by shirakaba** [comment]
`encoding` is an optional dependency of `node-fetch`. Have you tried installing it?

**Comment by cicada1993** [comment]
> `encoding` is an optional dependency of `node-fetch`. Have you tried installing it?

got it,thanks
