### ISSUE TITLE
Rendering Breaks if User Components Used

### ISSUE THREAD

**Issue by jsprog** [nodegui/svelte-nodegui#68]
**Description:**
- Rendering breaks if `App.svelte` used user components (e.g: `StepOne.svelte & StepTwo.svelte` in starter template). Please, refer to https://github.com/nodegui/svelte-nodegui-starter/issues/4 for image.
- This started from `@nodegui/svelte-nodegui@0.0.4`. The most recent version `@0.1.2` isn't fixing this.
- The **last version tested to work** without breaking the rendering is **`@nodegui/svelte-nodegui@0.0.3-alpha.1`**

**Test Platform:**
- Linux LMDE 4
- node.js/qode `v16.7.0 & v14.17.5`

**Comment by ceremcem** [comment]
Is there any progress on this?

**Comment by shirakaba** [comment]
I’ve no idea why layout is going strange as I haven’t changed the code since the last working release. I’ve tried a few combinations of dependencies with no luck. I’m not sure whether it’s a problem in Svelte NodeGUI, NodeGUI itself, Qt5, or computer environment. Until some clues emerge, I’m not sure how to proceed.

**Comment by ceremcem** [comment]
I don't understand if the layout is broken also for you or not. If it works for you, I would suggest setting up a virtual environment, which I find [nodeenv](https://github.com/ekalinin/nodeenv) useful.

I'm using Debian Buster and this release has [a known Qt5 issue](https://github.com/tasmota/tasmotizer/issues/71#issue-780883689), so it might be a Qt5 related issue. 

Debian Buster 
NodeJS: v12.22.6
Qt version: 5.11.3

**Comment by Levyks** [comment]
I'm having the same problem in Windows 11, so it's probably not an issue with Debian Buster

I've tested with Node v16.13.0 and v14.6.0

I used the `svelte-nodegui-starter` template with the version of `@nodegui/svelte-nodegui` bumped to 0.1.2

**Comment by shirakaba** [comment]
> I don't understand if the layout is broken also for you or not.

It’s broken for me on my M1 Mac but wasn’t last time I checked on my Intel Mac. I tried various different mixtures of dependencies, but my M1 Mac can’t run the same dependencies as the Intel one, so I can’t compare like-for-like.

When I have a free moment, I can try on my Intel Mac again, but I remember this issue being filed by others while it was still working perfectly fine on my Intel Mac.

**Comment by ceremcem** [comment]
Might this be related to the GCC version? Mine is: gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by shirakaba** [comment]
I doubt it. Could you try with `svelte-nodegui@0.0.4`, out of curiosity?

**Comment by Levyks** [comment]
> I doubt it. Could you try with `svelte-nodegui@0.0.3-alpha.1`, out of curiosity?

That fixed it for me, any significant changes from that version to the current ones?

**Comment by shirakaba** [comment]
Closed in favour of the more focused issue, #72.
