### ISSUE TITLE
Broken layout on Linux

### ISSUE THREAD

**Issue by M-Gonzalo** [nodegui/svelte-nodegui#73]
Image speaks for itself. I haven't touched the code yet, this is my first try with the skeleton repo.

System: Manjaro Linux x86-64 KDE, up-to-date.

![Screenshot_20220916_134458](https://user-images.githubusercontent.com/23223606/190689023-925c66c6-480d-46f4-966b-540ca77ae5ab.png)

**Comment by M-Gonzalo** [comment]
Hello... anyone here?

**Comment by shirakaba** [comment]
Layout seems to be broken on certain platforms since a certain version of nodegui and I haven't been able to figure out the reason. I don't have a Linux setup and couldn't get things to build/run on my M1 Mac last time I tried, so I'm afraid I can't investigate!

**Comment by M-Gonzalo** [comment]
React version works though

**Comment by shirakaba** [comment]
Useful info, but I’m afraid I can’t get it to run on my computer!

**Comment by dlight** [comment]
Is this related to #72?

**Comment by shirakaba** [comment]
Ah, yes. So the status on that is that we can either have:

- `@nodegui/svelte-nodegui@0.0.3-alpha.1`: working layout, but broken `{#each}`/`{#if}`;
- `@nodegui/svelte-nodegui@0.0.4` to the current latest version (`@nodegui/svelte-nodegui@0.1.2`), : working `{#each}`/`{#if}`, but broken layout.

Obviously neither of these is acceptable.

As mentioned in https://github.com/nodegui/svelte-nodegui/issues/72#issuecomment-1002714286, it may be something to do with user components getting interpreted as SVG despite setting up our preprocessor correctly (as far as I can tell). Perhaps some version of Svelte introduced during 2021 caused user components to be interpreted as SVG or something.
