### ISSUE TITLE
License of Qt?

### ISSUE THREAD

**Issue by microSoftware** [nodegui/svelte-nodegui#75]
I don't understand the license of Qt? 
Should my desktop application be open-source for me to use NodeGUI and therefore Qt ?
My application is going to be a commercial software. What kind of Qt license do i need for that?

**Comment by shayneoneill** [comment]
You should be fine. QT has an LGPL license. As long as you dont physically link the QT binaries, your fine. 

The rule of thumb is "If the user can remove the copy of QT and supply their own, its A-OK"
