### ISSUE TITLE
Possible need for a preprocessor

### ISSUE THREAD

**Issue by shirakaba** [nodegui/svelte-nodegui#9]
See https://github.com/halfnelson/svelte-native-preprocessor:

> It performs the following transforms to provide a better developer experience when using Svelte-Native:
> 
>  - [x] Adds `<svelte:options namespace="xmlns" />` to the component, ensuring the generated code is compatible with svelte-native
>  - [x] Changes `bind:text="{email}"` to `text="{email}" on:textChanged="{e => email = e.value}"`

We at least need the namespace aspect, as if PR https://github.com/sveltejs/svelte/pull/5652 lands, we'll require such preprocessing in order to close https://github.com/shirakaba/svelte-nodegui/issues/9.

I'm unsure whether we'll need it for `bind:text`; I haven't yet tried that feature (and indeed may not be able to if event listener names are forced to lower case – though I'm not sure of the casing used by NodeGUI yet).

**Comment by shirakaba** [comment]
I've published the preprocessor and incorporated it into both this repo's playground app and the official [svelte-nodegui-starter](https://github.com/nodegui/svelte-nodegui-starter). It works perfectly, thanks @mrsauravsahu!

**Comment by mrsauravsahu** [comment]
Ah thanks @shirakaba for taking the lead on this. Great to hear that! 😃
